name: Build & Test Decaf Compiler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison llvm clang python3

    - name: 🔧 Build compiler
      run: |
        cd answer
        make -f makefile.csil clean
        make -f makefile.csil decafexpr

    - name: Run tests
      run: |
        python3 check.py
